### ISSUE TITLE
Error in plot.new() : figure margins too large

### ISSUE THREAD

**Issue by bluepahl** [cran/MixSIAR#1]
Hello all, 

Trying to use the killer whale vingette as an example to run my own data. I have therefore formatted my csv files to look just like those of the killerwhale example sheets. The issues I am having are: 

1) after I try to run the generalist prior with an alpha of 1 I get an error message. So the code I use is:
plot_prior(alpha.prior=1, source, filename = "prior_plot_sharks_uninf")  

The following messages appear: 

*** NOTE ***

MixSIAR sorts the sources alphabetically. If you are using an informative
prior, please check the plot to confirm that the sources you meant to give 
greater weight in the alpha vector receive greater weight in the prior.

In addition: Warning messages:
1: In readChar(file, size, TRUE) : truncating string with embedded nuls
2: In readChar(file, size, TRUE) : truncating string with embedded nuls
3: In readChar(file, size, TRUE) : truncating string with embedded nuls
4: In readChar(file, size, TRUE) : truncating string with embedded nuls
5: In readChar(file, size, TRUE) : truncating string with embedded nuls

The error message received is: 
Error in plot.new() : figure margins too large

I tried the code par(mar=c(1,1,1,1)) but no dice. 

2) If I ignore that section of code and go onto writing and running the JAGS model, I get this error after the summary statistics
So the code is: 
model_filename <- "MixSIAR_model_BLA_uninf.txt"
resid_err <- TRUE
process_err <- TRUE
write_JAGS_model(model_filename, resid_err, process_err, mix, source)

jags.uninf <- run_model(run="test",mix,source,discr,model_filename,alpha.prior = 1, resid_err, process_err)
output_JAGS(jags.uninf, mix, source)

Error: Problem with `summarise()` input `n`. x could not find function "n" i Input `n` is `n()`. i The error occured in group 1: Parameter = "deviance", Chain = 1, part = "first".

^I should mention this last error happens when I'm trying to run the vingette code as well. 

Thanks for your help,
Blue.

**Comment by bluepahl** [comment]
I worked through it and realized I had too many source variables. Once I got them down to 5 I was fine for the isospace_plot. 
That appears to have cleared up the JAGS issue as well

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and potentially URLs in the `DESCRIPTION` file. Thanks!
